import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = {
  EN: { code: 'EN', name: 'English', flag: '🇺🇸', dir: 'ltr' },
  BN: { code: 'BN', name: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  ES: { code: 'ES', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  FR: { code: 'FR', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  AR: { code: 'AR', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  DE: { code: 'DE', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' }
};

const TRANSLATIONS = {
  EN: {
    // Nav & General
    home: 'Home',
    hotels: 'Hotels',
    offers: 'Offers',
    gallery: 'Gallery',
    contact: 'Contact',
    pages: 'Pages',
    about: 'About Us',
    blog: 'Blog Articles',
    faq: 'Help & FAQ',
    terms: 'Terms & Privacy',
    signIn: 'Sign In',
    register: 'Register',
    logout: 'Logout',
    publicPages: 'Public Pages',
    fullCatalog: 'Full Catalog',

    // Hero & Search
    heroTitle: 'Book Overwater Villas, Caldera Suites & Ski Chalets',
    heroSub: 'Instant QR stay vouchers, zero hidden fees, and guaranteed best prices at 5-star handpicked sanctuaries worldwide.',
    searchPlaceholder: 'Where to next? (e.g., Santorini, Maldives, Tokyo...)',
    searchButton: 'Search Luxury Stays',
    searchPropertyPlaceholder: 'e.g. Resort, Villa, Santorini...',
    allDestinations: 'All Destinations',
    allTypes: 'All Luxury Types',
    propertyType: 'Property Type',
    guests: 'Guests',
    dates: 'Check-in / Check-out',

    // Categories
    allSuites: 'All Suites',
    overwaterVillas: 'Overwater Villas',
    cliffsideResorts: 'Cliffside Resorts',
    citySkyTowers: 'City Sky Towers',
    zenRyokans: 'Zen Ryokans',
    skiChalets: 'Ski Chalets',
    resortSpas: 'Resorts & Spas',

    // Hotel Cards & Badges
    featuredSuites: 'Handpicked Signature Suites',
    curatedPortfolio: 'Curated Luxury Portfolio',
    viewSuite: 'View Suite',
    perNight: 'night',
    nightlyRate: 'Nightly Rate (Includes Taxes)',
    promoBanner: 'SPECIAL PROMO: Use code SUMMER20 for 20% off luxury villas!',
    freeBreakfast: 'Gourmet Breakfast Included',
    freeCancellation: 'Free Cancellation',
    qrVoucher: 'Instant QR Stay Voucher',
    ourGallery: 'Our Gallery',
    gallerySub: 'Immerse in private sanctuaries, gourmet dining, and beachfront tranquility',
    destinations: 'Popular Destinations',
    globalDestinations: 'Global Travel Destinations',
    exploreWorld: 'Explore World Destinations',
    properties: 'Properties',
    explore: 'Explore',
    verifiedGuest: '100% Verified Stays',
    verifiedSub: 'Every property passes our 50-point luxury inspection ensuring private plunge pools, butler service, and uncompromised privacy.',
    bestRate: 'Best Rate Guarantee',
    bestRateSub: 'Direct partner integration guarantees zero hidden broker markups with instant digital stay voucher generation.',
    concierge: '24/7 Dedicated Concierge',
    conciergeSub: 'Personalized airport VIP shuttles, Michelin tasting reservations, and customized itinerary management at your service.',
    guestExperiences: 'Verified Guest Experiences',
    lovedByTravelers: 'Loved by Discerning Travelers',
    superb: 'Superb',
    reviews: 'reviews',
    allPhotos: 'ALL PHOTOS',
    hotelGrounds: 'HOTEL & GROUNDS',
    roomsSuites: 'ROOMS & SUITES',
    fineDining: 'FINE DINING',
    spaWellness: 'SPA & WELLNESS',
    viewMore: 'VIEW MORE',
    unlockDiscount: 'Unlock 20% Off Your Next Escape',
    exclusivePromo: 'Exclusive Promo Voucher',
    viewPromos: 'View All Promos',

    // Catalog & Filters
    filterTitle: 'Filter Selection',
    resetFilters: 'Reset',
    maxPrice: 'Max Price / Night',
    anyPrice: 'Any Price',
    guestRating: 'Guest Rating',
    anyRating: 'Any Rating',
    exceptional: '4.8★ & Above (Exceptional)',
    superbRating: '4.5★ & Above (Superb)',
    veryGood: '4.0★ & Above (Very Good)',
    amenities: 'Signature Amenities',
    suitesFound: 'Suites Found',
    sortBy: 'Sort by:',
    topRated: 'Top Guest Rating',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    listView: 'Booking.com List View',
    gridView: 'Grid View',

    // Amenities
    infinityPool: 'Infinity Pool',
    privateBeach: 'Private Beach',
    luxurySpa: 'Luxury Spa',
    freeWifi: 'Free Wi-Fi',
    butlerService: 'Butler Service',
    helipadAccess: 'Helipad Access',
    michelinDining: 'Michelin Dining',
    skiInSkiOut: 'Ski-In Ski-Out',

    // Auth & Accounts
    welcomeBack: 'Welcome Back',
    createAccount: 'Create LuxeStay Account',
    customerAccount: 'Customer Account',
    partnerPortal: 'Partner Portal',
    guestAccount: 'Guest Account',
    fullNameLabel: 'FULL NAME *',
    emailLabel: 'EMAIL ADDRESS *',
    passwordLabel: 'PASSWORD *',
    forgotPassword: 'Forgot Password?',
    continueGoogle: 'Continue with Google',
    signUpGoogle: 'Sign Up with Google',
    adminDemo: '⚡ 1-Click Super Admin Demo Login',
    noAccount: "Don't have an account in LuxeStay?",
    haveAccount: 'Already have an account in LuxeStay?',
    registerNow: 'REGISTER NOW',
    signInNow: 'SIGN IN NOW',
    profilePicture: 'Profile Picture',
    optionalUpload: 'Optional photo upload'
  },

  BN: {
    // Nav & General
    home: 'হোম',
    hotels: 'হোটেলসমূহ',
    offers: 'অফারসমূহ',
    gallery: 'গ্যালারি',
    contact: 'যোগাযোগ',
    pages: 'পেজসমূহ',
    about: 'আমাদের সম্পর্কে',
    blog: 'ট্রাভেল ব্লগ',
    faq: 'সাহায্য ও প্রশ্নাবলী',
    terms: 'শর্তাবলী ও গোপনীয়তা',
    signIn: 'সাইন ইন',
    register: 'রেজিস্টার',
    logout: 'লগআউট',
    publicPages: 'পাবলিক পেজসমূহ',
    fullCatalog: 'সম্পূর্ণ ক্যাটালগ',

    // Hero & Search
    heroTitle: 'বুক করুন ওভারওয়াটার ভিলা, ক্যালডেরা সুইট এবং স্কি ক্যালেট',
    heroSub: 'তাৎক্ষণিক কিউআর ডিজিটাল ভাউচার, কোনো লুকানো ফি ছাড়াই সেরা মূল্যে বিশ্বের ৫-স্টার লাক্সারি রিসোর্ট বুক করুন।',
    searchPlaceholder: 'আপনার পরবর্তী গন্তব্য কোথায়? (যেমন: সান্তোরিনি, মালদ্বীপ...)',
    searchButton: 'লাক্সারি হোটেল খুঁজুন',
    searchPropertyPlaceholder: 'যেমন: রিসোর্ট, ভিলা, সান্তোরিনি...',
    allDestinations: 'সমস্ত গন্তব্যসমূহ',
    allTypes: 'সমস্ত লাক্সারি ক্যাটাগরি',
    propertyType: 'প্রোপার্টি টাইপ',
    guests: 'অতিথি সংখ্যা',
    dates: 'চেক-ইন / চেক-আউট',

    // Categories
    allSuites: 'সমস্ত সুইটসমূহ',
    overwaterVillas: 'ওভারওয়াটার ভিলা',
    cliffsideResorts: 'ক্লিফসাইড রিসোর্ট',
    citySkyTowers: 'সিটি স্কাই টাওয়ার',
    zenRyokans: 'জাপানিজ রিয়োকান',
    skiChalets: 'স্কি ক্যালেট',
    resortSpas: 'রিসোর্ট ও স্পা',

    // Hotel Cards & Badges
    featuredSuites: 'পছন্দসই সেরা লাক্সারি সুইটসমূহ',
    curatedPortfolio: 'নির্বাচিত লাক্সারি পোর্টফোলিও',
    viewSuite: 'সুইট দেখুন',
    perNight: 'রাত',
    nightlyRate: 'প্রতি রাতের মূল্য (ট্যাক্সসহ)',
    promoBanner: 'বিশেষ অফার: ২০% ছাড় পেতে SUMMER20 কোডটি ব্যবহার করুন!',
    freeBreakfast: 'ফ্রি বুফে প্রাতরাশ অন্তর্ভুক্ত',
    freeCancellation: 'বিনামূল্যে বুকিং বাতিল',
    qrVoucher: 'তাৎক্ষণিক কিউআর ডিজিটাল ভাউচার',
    ourGallery: 'আমাদের গ্যালারি',
    gallerySub: 'প্রাইভেট স্যুট, সুস্বাদু ডাইনিং ও সি-বীচের প্রশান্তিতে হারিয়ে যান',
    destinations: 'জনপ্রিয় গন্তব্যসমূহ',
    globalDestinations: 'গ্লোবাল ট্রাভেল ডেসটিনেশন',
    exploreWorld: 'বিশ্বের সেরা গন্তব্যসমূহ ঘুরে দেখুন',
    properties: 'টি প্রোপার্টি',
    explore: 'এক্সপ্লোর করুন',
    verifiedGuest: '১০০% যাচাইকৃত লাক্সারি স্টে',
    verifiedSub: 'প্রতিটি হোটেল আমাদের ৫০-পয়েন্ট লাক্সারি ইন্সপেকশন পার হয়ে যুক্ত হয়।',
    bestRate: 'সেরা মূল্যের গ্যারান্টি',
    bestRateSub: 'সরাসরি পার্টনার সংযোগের কারণে কোনো হিডেন চার্জ ছাড়াই বুকিং সুবিধা।',
    concierge: '২৪/৭ ডেডিকেটেড কনসিয়ার্জ সেবা',
    conciergeSub: 'ব্যক্তিগত এয়ারপোর্ট ভিআইপি শাটল ও মিশেলিন ডাইনিং রিজার্ভেশন সুবিধা।',
    guestExperiences: 'যাচাইকৃত গেস্ট অভিজ্ঞতা',
    lovedByTravelers: 'পর্যটকদের প্রিয় আন্তর্জাতিক পছন্দ',
    superb: 'চমৎকার',
    reviews: 'টি রিভিউ',
    allPhotos: 'সমস্ত ছবি',
    hotelGrounds: 'হোটেল ও প্রাঙ্গণ',
    roomsSuites: 'রুম ও সুইটসমূহ',
    fineDining: 'ফাইন ডাইনিং',
    spaWellness: 'স্পা ও ওয়েলনেস',
    viewMore: 'আরো দেখুন',
    unlockDiscount: 'আপনার পরবর্তী ট্রিপে ২০% ছাড় উপভোগ করুন',
    exclusivePromo: 'এক্সক্লুসিভ প্রমো ভাউচার',
    viewPromos: 'সমস্ত প্রমো দেখুন',

    // Catalog & Filters
    filterTitle: 'ফিল্টার নির্বাচন',
    resetFilters: 'রিসেট',
    maxPrice: 'সর্বোচ্চ মূল্য / রাত',
    anyPrice: 'যেকোনো মূল্য',
    guestRating: 'গেস্ট রেটিং',
    anyRating: 'যেকোনো রেটিং',
    exceptional: '৪.৮★ ও ওপরে (ব্যতিক্রমী)',
    superbRating: '৪.৫★ ও ওপরে (চমৎকার)',
    veryGood: '৪.০★ ও ওপরে (খুব ভালো)',
    amenities: 'বিশেষ সুযোগ-সুবিধা',
    suitesFound: 'টি সুইট পাওয়া গেছে',
    sortBy: 'সাজান:',
    topRated: 'সর্বোচ্চ রেটিংপ্রাপ্ত',
    priceLowHigh: 'মূল্য: কম থেকে বেশি',
    priceHighLow: 'মূল্য: বেশি থেকে কম',
    listView: 'লিস্ট ভিউ',
    gridView: 'গ্রিড ভিউ',

    // Amenities
    infinityPool: 'ইনফিনিটি পুল',
    privateBeach: 'প্রাইভেট বিচ',
    luxurySpa: 'লাক্সারি স্পা',
    freeWifi: 'ফ্রি ওয়াই-ফাই',
    butlerService: 'পার্সোনাল বাটলার সার্ভিস',
    helipadAccess: 'হেলিপ্যাড সুবিধা',
    michelinDining: 'মিশেলিন ডাইনিং',
    skiInSkiOut: 'স্কি-ইন স্কি-আউট',

    // Auth & Accounts
    welcomeBack: 'পুনরায় স্বাগতম',
    createAccount: 'লাক্সস্টে অ্যাকাউন্ট তৈরি করুন',
    customerAccount: 'কাস্টমার অ্যাকাউন্ট',
    partnerPortal: 'পার্টনার পোর্টাল',
    guestAccount: 'গেস্ট অ্যাকাউন্ট',
    fullNameLabel: 'সম্পূর্ণ নাম *',
    emailLabel: 'ইমেইল অ্যাড্রেস *',
    passwordLabel: 'পাসওয়ার্ড *',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    continueGoogle: 'গুগল দিয়ে প্রবেশ করুন',
    signUpGoogle: 'গুগল দিয়ে সাইন আপ করুন',
    adminDemo: '⚡ ১-ক্লিক সুপার অ্যাডমিন ডেমো লগইন',
    noAccount: 'লাক্সস্টে-তে কোনো অ্যাকাউন্ট নেই?',
    haveAccount: 'ইতিমধ্যেই লাক্সস্টে অ্যাকাউন্ট আছে?',
    registerNow: 'এখনই রেজিস্টার করুন',
    signInNow: 'এখনই সাইন ইন করুন',
    profilePicture: 'প্রোফাইল পিকচার',
    optionalUpload: 'ঐচ্ছিক ছবি আপলোড'
  },

  ES: {
    home: 'Inicio',
    hotels: 'Hoteles',
    offers: 'Ofertas',
    gallery: 'Galería',
    contact: 'Contacto',
    pages: 'Páginas',
    about: 'Nosotros',
    blog: 'Blog de Viajes',
    faq: 'Ayuda y Preguntas',
    terms: 'Términos y Privacidad',
    signIn: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    publicPages: 'Páginas Públicas',
    fullCatalog: 'Catálogo Completo',

    heroTitle: 'Reserva Villas Sobre el Agua y Suites de Lujo',
    heroSub: 'Vouchers digitales instantáneos QR sin cargos ocultos en los mejores resorts de 5 estrellas del mundo.',
    searchPlaceholder: '¿A dónde viajas? (ej. Santorini, Maldivas...)',
    searchButton: 'Buscar Hoteles de Lujo',
    searchPropertyPlaceholder: 'ej. Resort, Villa, Santorini...',
    allDestinations: 'Todos los Destinos',
    allTypes: 'Todos los Tipos',
    propertyType: 'Tipo de Propiedad',
    guests: 'Huéspedes',
    dates: 'Entrada / Salida',

    allSuites: 'Todas las Suites',
    overwaterVillas: 'Villas Sobre el Agua',
    cliffsideResorts: 'Resorts de Acantilado',
    citySkyTowers: 'Torres Urbanas de Lujo',
    zenRyokans: 'Ryokans Tradicionales',
    skiChalets: 'Chalets de Esquí',
    resortSpas: 'Resorts y Spas',

    featuredSuites: 'Suites de Lujo Destacadas',
    curatedPortfolio: 'Portafolio de Lujo Seleccionado',
    viewSuite: 'Ver Suite',
    perNight: 'noche',
    nightlyRate: 'Tarifa por Noche (Impuestos Incluidos)',
    promoBanner: 'OFERTA ESPECIAL: ¡20% de descuento con el código SUMMER20!',
    freeBreakfast: 'Desayuno Gourmet Incluido',
    freeCancellation: 'Cancelación Gratuita',
    qrVoucher: 'Voucher QR Instantáneo',
    ourGallery: 'Nuestra Galería',
    gallerySub: 'Sumérgete en santuarios privados y gastronomía de lujo',
    destinations: 'Destinos Populares',
    globalDestinations: 'Destinos Globales de Viaje',
    exploreWorld: 'Explora Destinos Mundiales',
    properties: 'Propiedades',
    explore: 'Explorar',
    verifiedGuest: 'Estancias 100% Verificadas',
    verifiedSub: 'Cada propiedad supera nuestra inspección de lujo de 50 puntos.',
    bestRate: 'Garantía del Mejor Precio',
    bestRateSub: 'Integración directa con socios sin comisiones ocultas.',
    concierge: 'Conserjería 24/7',
    conciergeSub: 'Traslados VIP de aeropuerto y reservas exclusivas a su servicio.',
    guestExperiences: 'Experiencias de Huéspedes Verificados',
    lovedByTravelers: 'Amado por Viajeros Exigentes',
    superb: 'Excelente',
    reviews: 'opiniones',
    allPhotos: 'TODAS LAS FOTOS',
    hotelGrounds: 'HOTEL Y TERRENOS',
    roomsSuites: 'HABITACIONES Y SUITES',
    fineDining: 'GASTRONOMÍA DE LUJO',
    spaWellness: 'SPA Y BIENESTAR',
    viewMore: 'VER MÁS',
    unlockDiscount: 'Desbloquea un 20% de Descuento en tu Próxima Escapada',
    exclusivePromo: 'Voucher Promocional Exclusivo',
    viewPromos: 'Ver Promociones',

    filterTitle: 'Filtros de Búsqueda',
    resetFilters: 'Reiniciar',
    maxPrice: 'Precio Máx / Noche',
    anyPrice: 'Cualquier Precio',
    guestRating: 'Valoración',
    anyRating: 'Cualquier Valoración',
    exceptional: '4.8★ y Más (Excepcional)',
    superbRating: '4.5★ y Más (Excelente)',
    veryGood: '4.0★ y Más (Muy Bueno)',
    amenities: 'Servicios de Lujo',
    suitesFound: 'Suites Encontradas',
    sortBy: 'Ordenar por:',
    topRated: 'Mejor Valorados',
    priceLowHigh: 'Precio: Menor a Mayor',
    priceHighLow: 'Precio: Mayor a Menor',
    listView: 'Vista en Lista',
    gridView: 'Vista en Cuadrícula',

    infinityPool: 'Piscina Infinity',
    privateBeach: 'Playa Privada',
    luxurySpa: 'Spa de Lujo',
    freeWifi: 'Wi-Fi Gratis',
    butlerService: 'Servicio de Mayordomo',
    helipadAccess: 'Helipuerto',
    michelinDining: 'Restaurante Michelin',
    skiInSkiOut: 'Acceso a Pista de Esquí',

    welcomeBack: 'Bienvenido de Nuevo',
    createAccount: 'Crear Cuenta LuxeStay',
    customerAccount: 'Cuenta de Cliente',
    partnerPortal: 'Portal de Socios',
    guestAccount: 'Cuenta de Huésped',
    fullNameLabel: 'NOMBRE COMPLETO *',
    emailLabel: 'CORREO ELECTRÓNICO *',
    passwordLabel: 'CONTRASEÑA *',
    forgotPassword: '¿Olvidaste tu contraseña?',
    continueGoogle: 'Continuar con Google',
    signUpGoogle: 'Registrarse con Google',
    adminDemo: '⚡ Demo Admin 1-Clic',
    noAccount: '¿No tienes cuenta en LuxeStay?',
    haveAccount: '¿Ya tienes una cuenta?',
    registerNow: 'REGÍSTRATE AHORA',
    signInNow: 'INICIA SESIÓN AHORA',
    profilePicture: 'Foto de Perfil',
    optionalUpload: 'Carga de foto opcional'
  },

  FR: {
    home: 'Accueil',
    hotels: 'Hôtels',
    offers: 'Offres',
    gallery: 'Galerie',
    contact: 'Contact',
    pages: 'Pages',
    about: 'À Propos',
    blog: 'Blog de Voyage',
    faq: 'Aide & FAQ',
    terms: 'Conditions & Confidentialité',
    signIn: 'Se Connecter',
    register: "S'inscrire",
    logout: 'Déconnexion',
    publicPages: 'Pages Publiques',
    fullCatalog: 'Catalogue Complet',

    heroTitle: 'Réservez des Villas Sur l\'Eau et des Suites d\'Exception',
    heroSub: 'Bons QR numériques instantanés sans frais cachés dans les meilleurs établissements 5 étoiles.',
    searchPlaceholder: 'Où souhaitez-vous aller ? (ex: Santorin, Maldives...)',
    searchButton: 'Rechercher des Hôtels de Luxe',
    searchPropertyPlaceholder: 'ex: Resort, Villa, Santorin...',
    allDestinations: 'Toutes les Destinations',
    allTypes: 'Tous les Types',
    propertyType: 'Type d\'Établissement',
    guests: 'Voyageurs',
    dates: 'Arrivée / Départ',

    allSuites: 'Toutes les Suites',
    overwaterVillas: 'Villas Sur l\'Eau',
    cliffsideResorts: 'Resorts de Falaise',
    citySkyTowers: 'Tours Urbaines de Luxe',
    zenRyokans: 'Ryokans Traditionnels',
    skiChalets: 'Chalets de Ski',
    resortSpas: 'Resorts & Spas',

    featuredSuites: 'Suites de Luxe Sélectionnées',
    curatedPortfolio: 'Portfolio de Luxe Sélectionné',
    viewSuite: 'Voir la Suite',
    perNight: 'nuit',
    nightlyRate: 'Tarif par Nuit (Taxes Incluses)',
    promoBanner: 'PROMOTION SPECIALE: -20% avec le code SUMMER20 !',
    freeBreakfast: 'Petit-déjeuner Gourmet Inclus',
    freeCancellation: 'Annulation Gratuite',
    qrVoucher: 'Voucher QR Instantané',
    ourGallery: 'Notre Galerie',
    gallerySub: 'Plongez dans des sanctuaires privés et une gastronomie raffinée',
    destinations: 'Destinations Populaires',
    globalDestinations: 'Destinations de Voyage Mondiales',
    exploreWorld: 'Explorez les Destinations du Monde',
    properties: 'Établissements',
    explore: 'Explorer',
    verifiedGuest: 'Séjours 100% Vérifiés',
    verifiedSub: 'Chaque établissement réussit notre inspection de luxe en 50 points.',
    bestRate: 'Garantie du Meilleur Tarif',
    bestRateSub: 'Intégration directe avec les partenaires sans frais cachés.',
    concierge: 'Conciergerie Dédiée 24/7',
    conciergeSub: 'Navettes VIP aéroport et réservations exclusives à votre service.',
    guestExperiences: 'Avis Clients Vérifiés',
    lovedByTravelers: 'Apprécié des Voyageurs Exigeants',
    superb: 'Superbe',
    reviews: 'avis',
    allPhotos: 'TOUTES LES PHOTOS',
    hotelGrounds: 'HÔTEL & DOMAINE',
    roomsSuites: 'CHAMBRES & SUITES',
    fineDining: 'GASTRONOMIE',
    spaWellness: 'SPA & BIEN-ÊTRE',
    viewMore: 'VOIR PLUS',
    unlockDiscount: 'Obtenez -20% sur Votre Prochain Séjour',
    exclusivePromo: 'Voucher Promo Exclusif',
    viewPromos: 'Voir les Promos',

    filterTitle: 'Sélection des Filtres',
    resetFilters: 'Réinitialiser',
    maxPrice: 'Prix Max / Nuit',
    anyPrice: 'Tous les Prix',
    guestRating: 'Avis Clients',
    anyRating: 'Toutes les Notes',
    exceptional: '4.8★ & Plus (Exceptionnel)',
    superbRating: '4.5★ & Plus (Superbe)',
    veryGood: '4.0★ & Plus (Très Bon)',
    amenities: 'Équipements de Luxe',
    suitesFound: 'Suites Trouvées',
    sortBy: 'Trier par :',
    topRated: 'Mieux Notés',
    priceLowHigh: 'Prix : Croissant',
    priceHighLow: 'Prix : Décroissant',
    listView: 'Vue Liste',
    gridView: 'Vue Grille',

    infinityPool: 'Piscine Débordante',
    privateBeach: 'Plage Privée',
    luxurySpa: 'Spa de Luxe',
    freeWifi: 'Wi-Fi Gratuit',
    butlerService: 'Majordome Privé',
    helipadAccess: 'Héliport',
    michelinDining: 'Table Étoilée',
    skiInSkiOut: 'Accès Direct aux Pistes',

    welcomeBack: 'Bon Retour Parmi Nous',
    createAccount: 'Créer un Compte LuxeStay',
    customerAccount: 'Compte Client',
    partnerPortal: 'Portail Partenaire',
    guestAccount: 'Compte Invité',
    fullNameLabel: 'NOM COMPLET *',
    emailLabel: 'ADRESSE EMAIL *',
    passwordLabel: 'MOT DE PASSE *',
    forgotPassword: 'Mot de passe oublié ?',
    continueGoogle: 'Continuer avec Google',
    signUpGoogle: 'S\'inscrire avec Google',
    adminDemo: '⚡ Connexion Démo Admin 1-Clic',
    noAccount: "Vous n'avez pas de compte LuxeStay ?",
    haveAccount: 'Vous avez déjà un compte ?',
    registerNow: 'S\'INSCRIRE MAINTENANT',
    signInNow: 'SE CONNECTER MAINTENANT',
    profilePicture: 'Photo de Profil',
    optionalUpload: 'Chargement de photo optionnel'
  },

  AR: {
    home: 'الرئيسية',
    hotels: 'الفنادق',
    offers: 'العروض',
    gallery: 'معرض الصور',
    contact: 'اتصل بنا',
    pages: 'الصفحات',
    about: 'معلومات عنا',
    blog: 'مدونة السفر',
    faq: 'المساعدة والأسئلة',
    terms: 'الشروط والخصوصية',
    signIn: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    publicPages: 'الصفحات العامة',
    fullCatalog: 'الكتالوج الكامل',

    heroTitle: 'احجز فيلات فوق الماء وأجنحة فاخرة',
    heroSub: 'قسائم إقامة رقمية فورية بدون رسوم مخفية في أرقى المنتجات الفاخرة 5 نجوم.',
    searchPlaceholder: 'إلى أين وجهتك القادمة؟ (مثال: سانتوريني، المالديف...)',
    searchButton: 'البحث عن الفنادق الفاخرة',
    searchPropertyPlaceholder: 'مثال: منتجع، فيلا، سانتوريني...',
    allDestinations: 'جميع الوجهات',
    allTypes: 'جميع الأنواع الفاخرة',
    propertyType: 'نوع العقار',
    guests: 'الضيوف',
    dates: 'الوصول / المغادرة',

    allSuites: 'جميع الأجنحة',
    overwaterVillas: 'فيلات فوق الماء',
    cliffsideResorts: 'منتجعات جبلية',
    citySkyTowers: 'أبراج فاخرة',
    zenRyokans: 'ريوكان ياباني',
    skiChalets: 'شاليهات التزلج',
    resortSpas: 'منتجعات وسبا',

    featuredSuites: 'أجنحة فاخرة مختارة بعناية',
    curatedPortfolio: 'مجموعة فاخرة مختارة',
    viewSuite: 'عرض الجناح',
    perNight: 'ليلة',
    nightlyRate: 'السعر لكل ليلة (شامل الضرائب)',
    promoBanner: 'عرض خاص: خصم 20% باستخدام كود SUMMER20!',
    freeBreakfast: 'إفطار فاخر مشمول',
    freeCancellation: 'إلغاء مجاني',
    qrVoucher: 'قسيمة QR فورية',
    ourGallery: 'معرض الصور الخاص بنا',
    gallerySub: 'استمتع بالهدوء التام والوجبات الفاخرة في ملاذات خاصة',
    destinations: 'الوجهات الشهيرة',
    globalDestinations: 'وجهات السفر العالمية',
    exploreWorld: 'استكشف الوجهات العالمية',
    properties: 'عقارات',
    explore: 'استكشاف',
    verifiedGuest: 'إقامات موثقة 100%',
    verifiedSub: 'تخضع جميع العقارات لفحص الجودة الفاخرة 50 نقطة.',
    bestRate: 'ضمان أفضل سعر',
    bestRateSub: 'ربط مباشر بدون عمولات مخفية مع قسائم فورية.',
    concierge: 'خدمة خادم مخصصة 24/7',
    conciergeSub: 'توصيل VIP للمطار وحجوزات مطاعم فاخرة تحت خدمتك.',
    guestExperiences: 'تجارب الضيوف الموثقة',
    lovedByTravelers: 'المفضل لدى المسافرين المميزين',
    superb: 'ممتاز',
    reviews: 'تقييمات',
    allPhotos: 'جميع الصور',
    hotelGrounds: 'الفندق والمرافق',
    roomsSuites: 'الغرف والأجنحة',
    fineDining: 'المطاعم الفاخرة',
    spaWellness: 'السبا والعافية',
    viewMore: 'عرض المزيد',
    unlockDiscount: 'احصل على خصم 20% على إقامتك القادمة',
    exclusivePromo: 'قسيمة خصم حصرية',
    viewPromos: 'عرض جميع العروض',

    filterTitle: 'تصفية النتائج',
    resetFilters: 'إعادة ضبط',
    maxPrice: 'أقصى سعر / ليلة',
    anyPrice: 'أي سعر',
    guestRating: 'تقييم الضيوف',
    anyRating: 'أي تقييم',
    exceptional: '4.8★ وأعلى (استثنائي)',
    superbRating: '4.5★ وأعلى (ممتاز)',
    veryGood: '4.0★ وأعلى (جيد جداً)',
    amenities: 'المرافق الفاخرة',
    suitesFound: 'أجنحة متوفرة',
    sortBy: 'ترتيب حسب:',
    topRated: 'الأعلى تقييماً',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    listView: 'عرض القائمة',
    gridView: 'عرض الشبكة',

    infinityPool: 'مسبح إنفينيتي',
    privateBeach: 'شاطئ خاص',
    luxurySpa: 'سبا فاخر',
    freeWifi: 'واي فاي مجاني',
    butlerService: 'خادم شخصي',
    helipadAccess: 'مهبط مروحيات',
    michelinDining: 'مطاعم ميشلان',
    skiInSkiOut: 'وصول مباشر للمنحدرات',

    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب LuxeStay',
    customerAccount: 'حساب العميل',
    partnerPortal: 'بوابة الشركاء',
    guestAccount: 'حساب الضيف',
    fullNameLabel: 'الاسم الكامل *',
    emailLabel: 'البريد الإلكتروني *',
    passwordLabel: 'كلمة المرور *',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    continueGoogle: 'المتابعة بواسطة Google',
    signUpGoogle: 'التسجيل بواسطة Google',
    adminDemo: '⚡ دخول تجريبي سريع للمشرف',
    noAccount: 'ليس لديك حساب في LuxeStay؟',
    haveAccount: 'لديك حساب بالفعل؟',
    registerNow: 'سجل الآن',
    signInNow: 'سجل الدخول الآن',
    profilePicture: 'الصورة الشخصية',
    optionalUpload: 'رفع صورة اختياري'
  },

  DE: {
    home: 'Startseite',
    hotels: 'Hotels',
    offers: 'Angebote',
    gallery: 'Galerie',
    contact: 'Kontakt',
    pages: 'Seiten',
    about: 'Über Uns',
    blog: 'Reiseblog',
    faq: 'Hilfe & FAQ',
    terms: 'AGB & Datenschutz',
    signIn: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    publicPages: 'Öffentliche Seiten',
    fullCatalog: 'Vollständiger Katalog',

    heroTitle: 'Buchen Sie Überwasservillen & Exklusive Suiten',
    heroSub: 'Sofortige digitale QR-Gutscheine ohne versteckte Gebühren in erstklassigen 5-Sterne-Resorts weltweit.',
    searchPlaceholder: 'Wohin soll die Reise gehen? (z.B. Santorin, Malediven...)',
    searchButton: 'Luxushotels Suchen',
    searchPropertyPlaceholder: 'z.B. Resort, Villa, Santorin...',
    allDestinations: 'Alle Reiseziele',
    allTypes: 'Alle Luxus-Kategorien',
    propertyType: 'Unterkunftsart',
    guests: 'Gäste',
    dates: 'Anreise / Abreise',

    allSuites: 'Alle Suiten',
    overwaterVillas: 'Überwasservillen',
    cliffsideResorts: 'Klippen-Resorts',
    citySkyTowers: 'Stadt-Luxustürme',
    zenRyokans: 'Traditionelle Ryokans',
    skiChalets: 'Skichalets',
    resortSpas: 'Resorts & Spas',

    featuredSuites: 'Ausgewählte Luxussuiten',
    curatedPortfolio: 'Kuratierte Luxusauswahl',
    viewSuite: 'Suite Ansehen',
    perNight: 'Nacht',
    nightlyRate: 'Preis pro Nacht (Inkl. Steuern)',
    promoBanner: 'SONDERAKTION: 20% Rabatt mit Code SUMMER20!',
    freeBreakfast: 'Gourmet-Frühstück Inklusive',
    freeCancellation: 'Kostenlose Stornierung',
    qrVoucher: 'Sofortiger QR-Gutschein',
    ourGallery: 'Unsere Galerie',
    gallerySub: 'Tauchen Sie ein in private Zufluchtsorte und feine Gastronomie',
    destinations: 'Beliebte Reiseziele',
    globalDestinations: 'Weltweite Reiseziele',
    exploreWorld: 'Entdecken Sie Weltweite Reiseziele',
    properties: 'Unterkünfte',
    explore: 'Entdecken',
    verifiedGuest: '100% Geprüfte Unterkünfte',
    verifiedSub: 'Jede Unterkunft besteht unsere 50-Punkte-Luxusprüfung.',
    bestRate: 'Bestpreisgarantie',
    bestRateSub: 'Direkte Partnerintegration ohne versteckte Gebühren.',
    concierge: '24/7 Concierge-Service',
    conciergeSub: 'Individueller VIP-Flughafentransfer zu Ihren Diensten.',
    guestExperiences: 'Verifizierte Gästebewertungen',
    lovedByTravelers: 'Beliebt bei Anspruchsvollen Reisenden',
    superb: 'Hervorragend',
    reviews: 'Bewertungen',
    allPhotos: 'ALLE FOTOS',
    hotelGrounds: 'HOTEL & ANLAGE',
    roomsSuites: 'ZIMMER & SUITEN',
    fineDining: 'GASTRONOMIE',
    spaWellness: 'SPA & WELLNESS',
    viewMore: 'MEHR ANSEHEN',
    unlockDiscount: 'Sichern Sie sich 20% Rabatt auf Ihre Nächste Reise',
    exclusivePromo: 'Exklusiver Aktionsgutschein',
    viewPromos: 'Alle Angebote Ansehen',

    filterTitle: 'Filterauswahl',
    resetFilters: 'Zurücksetzen',
    maxPrice: 'Max. Preis / Nacht',
    anyPrice: 'Jeder Preis',
    guestRating: 'Bewertung',
    anyRating: 'Jede Bewertung',
    exceptional: '4.8★ & Höher (Außergewöhnlich)',
    superbRating: '4.5★ & Höher (Hervorragend)',
    veryGood: '4.0★ & Höher (Sehr Gut)',
    amenities: 'Exklusive Ausstattung',
    suitesFound: 'Suiten Gefunden',
    sortBy: 'Sortieren nach:',
    topRated: 'Beste Bewertung',
    priceLowHigh: 'Preis: Aufsteigend',
    priceHighLow: 'Preis: Absteigend',
    listView: 'Listenansicht',
    gridView: 'Rasteransicht',

    infinityPool: 'Infinity-Pool',
    privateBeach: 'Privatstrand',
    luxurySpa: 'Luxus-Spa',
    freeWifi: 'Kostenloses WLAN',
    butlerService: 'Butler-Service',
    helipadAccess: 'Hubschrauberlandeplatz',
    michelinDining: 'Michelin-Gastronomie',
    skiInSkiOut: 'Direkter Pistenzugang',

    welcomeBack: 'Willkommen Zurück',
    createAccount: 'LuxeStay Konto Erstellen',
    customerAccount: 'Kundenkonto',
    partnerPortal: 'Partnerportal',
    guestAccount: 'Gastkonto',
    fullNameLabel: 'VOLLSTÄNDIGER NAME *',
    emailLabel: 'E-MAIL-ADRESSE *',
    passwordLabel: 'PASSWORT *',
    forgotPassword: 'Passwort vergessen?',
    continueGoogle: 'Mit Google Fortfahren',
    signUpGoogle: 'Mit Google Registrieren',
    adminDemo: '⚡ 1-Klick Admin Demo Login',
    noAccount: 'Noch kein Konto bei LuxeStay?',
    haveAccount: 'Bereits ein Konto vorhanden?',
    registerNow: 'JETZT REGISTRIEREN',
    signInNow: 'JETZT ANMELDEN',
    profilePicture: 'Profilbild',
    optionalUpload: 'Optionaler Foto-Upload'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('luxestay_lang') || 'EN';
  });

  const setLanguage = (langCode) => {
    if (LANGUAGES[langCode]) {
      setLanguageState(langCode);
      localStorage.setItem('luxestay_lang', langCode);
      
      document.documentElement.dir = LANGUAGES[langCode].dir;
      document.documentElement.lang = langCode.toLowerCase();
    }
  };

  useEffect(() => {
    if (LANGUAGES[language]) {
      document.documentElement.dir = LANGUAGES[language].dir;
      document.documentElement.lang = language.toLowerCase();
    }
  }, [language]);

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
