import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = {
  EN: { code: 'EN', name: 'English', flag: '🇺🇸', dir: 'ltr' },
  BN: { code: 'BN', name: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  ES: { code: 'ES', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  FR: { code: 'FR', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  AR: { code: 'AR', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  DE: { code: 'DE', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' }
};

const TRANSLATIONS = {
  EN: {
    // Nav & General
    home: 'Home',
    hotels: 'Hotels',
    offers: 'Offers',
    gallery: 'Gallery',
    contact: 'Contact',
    pages: 'Pages',
    about: 'About Us',
    blog: 'Blog Articles',
    faq: 'Help & FAQ',
    terms: 'Terms & Privacy',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    signIn: 'Sign In',
    register: 'Register',
    logout: 'Logout',
    publicPages: 'Public Pages',
    fullCatalog: 'Full Catalog',
    customerPortals: 'Customer & Portals',
    customerDashboard: 'Customer Dashboard',
    partnerDashboard: 'Manager Dashboard',
    adminDashboard: 'Admin Dashboard',
    myBookings: 'My Bookings',
    savedWishlist: 'Saved Wishlist',
    customerProfile: 'Profile Settings',
    listYourProperty: 'List Your Property',
    notifications: 'Notifications',
    allCaughtUp: 'All caught up',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    noNotifSub: "You're all caught up for now!",
    viewDashboard: 'View Dashboard',
    exploreOffers: 'Explore Offers',
    unreadAlerts: 'unread alerts',
    alerts: 'LuxeStay Alerts',

    // Hero & Search
    heroTitle: 'Book Overwater Villas, Caldera Suites & Ski Chalets',
    heroSub: 'Instant QR stay vouchers, zero hidden fees, and guaranteed best prices at 5-star handpicked sanctuaries worldwide.',
    searchPlaceholder: 'Where to next? (e.g., Santorini, Maldives, Tokyo...)',
    searchButton: 'Search Luxury Stays',
    searchPropertyPlaceholder: 'e.g. Resort, Villa, Santorini...',
    allDestinations: 'All Destinations',
    allTypes: 'All Luxury Types',
    propertyType: 'Property Type',
    guests: 'Guests',
    dates: 'Check-in / Check-out',
    checkIn: 'Check-In',
    checkOut: 'Check-Out',
    whereToNext: 'Where to next?',
    guestCount: 'Guests & Rooms',
    searchNow: 'Search Now',

    // Categories
    allSuites: 'All Suites',
    overwaterVillas: 'Overwater Villas',
    cliffsideResorts: 'Cliffside Resorts',
    citySkyTowers: 'City Sky Towers',
    zenRyokans: 'Zen Ryokans',
    skiChalets: 'Ski Chalets',
    resortSpas: 'Resorts & Spas',

    // Hotel Cards & Badges
    featuredSuites: 'Handpicked Signature Suites',
    curatedPortfolio: 'Curated Luxury Portfolio',
    viewSuite: 'View Suite',
    bookNow: 'Book Now',
    reserveSuite: 'Reserve Suite',
    perNight: 'night',
    nightlyRate: 'Nightly Rate (Includes Taxes)',
    promoBanner: 'SPECIAL PROMO: Use code SUMMER20 for 20% off luxury villas!',
    freeBreakfast: 'Gourmet Breakfast Included',
    freeCancellation: 'Free Cancellation',
    qrVoucher: 'Instant QR Stay Voucher',
    ourGallery: 'Our Gallery',
    gallerySub: 'Immerse in private sanctuaries, gourmet dining, and beachfront tranquility',
    destinations: 'Popular Destinations',
    globalDestinations: 'Global Travel Destinations',
    exploreWorld: 'Explore World Destinations',
    properties: 'Properties',
    explore: 'Explore',
    verifiedGuest: '100% Verified Stays',
    verifiedSub: 'Every property passes our 50-point luxury inspection ensuring private plunge pools, butler service, and uncompromised privacy.',
    bestRate: 'Best Rate Guarantee',
    bestRateSub: 'Direct partner integration guarantees zero hidden broker markups with instant digital stay voucher generation.',
    concierge: '24/7 Dedicated Concierge',
    conciergeSub: 'Personalized airport VIP shuttles, Michelin tasting reservations, and customized itinerary management at your service.',
    guestExperiences: 'Verified Guest Experiences',
    lovedByTravelers: 'Loved by Discerning Travelers',
    superb: 'Superb',
    reviews: 'reviews',
    allPhotos: 'ALL PHOTOS',
    hotelGrounds: 'HOTEL & GROUNDS',
    roomsSuites: 'ROOMS & SUITES',
    fineDining: 'FINE DINING',
    spaWellness: 'SPA & WELLNESS',
    viewMore: 'VIEW MORE',
    unlockDiscount: 'Unlock 20% Off Your Next Escape',
    exclusivePromo: 'Exclusive Promo Voucher',
    viewPromos: 'View All Promos',
    spotlightTitle: 'Spotlight Luxury Deals',
    spotlightSub: 'Curated handpicked villas with limited-time promotional rates and complimentary VIP perks',
    flashSale: 'FLASH SALE',

    // Catalog & Filters
    filterTitle: 'Filter Selection',
    resetFilters: 'Reset',
    maxPrice: 'Max Price / Night',
    anyPrice: 'Any Price',
    guestRating: 'Guest Rating',
    anyRating: 'Any Rating',
    exceptional: '4.8★ & Above (Exceptional)',
    superbRating: '4.5★ & Above (Superb)',
    veryGood: '4.0★ & Above (Very Good)',
    amenities: 'Signature Amenities',
    suitesFound: 'Suites Found',
    sortBy: 'Sort by:',
    topRated: 'Top Guest Rating',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    listView: 'Booking.com List View',
    gridView: 'Grid View',
    noHotelsFound: 'No luxury suites match your current filter criteria.',
    clearFilters: 'Clear All Filters',

    // Amenities
    infinityPool: 'Infinity Pool',
    privateBeach: 'Private Beach',
    luxurySpa: 'Luxury Spa',
    freeWifi: 'Free Wi-Fi',
    butlerService: 'Butler Service',
    helipadAccess: 'Helipad Access',
    michelinDining: 'Michelin Dining',
    skiInSkiOut: 'Ski-In Ski-Out',
    privateJacuzzi: 'Private Jacuzzi',
    airportShuttle: 'Airport VIP Shuttle',

    // Detail & Rooms
    roomDetails: 'Suite & Room Details',
    sleeps: 'Sleeps',
    sqFt: 'sq ft',
    roomCapacity: 'Max Capacity',
    diningPackages: 'Dining & Meal Plan Options',
    curatedAddons: 'Curated Luxury Add-Ons',
    stayDates: 'Stay Dates & Guests',
    proceedCheckout: 'Proceed to Checkout',
    roomReservedNotice: 'ROOM RESERVED FOR THESE DATES',

    // Voucher & Receipt
    officialVoucher: 'Official Stay Voucher & Reservation Receipt',
    verifiedAndPaid: 'VERIFIED & PAID',
    holdGuaranteed: 'HOLD GUARANTEED • PAY AT CHECK-IN',
    bookingReference: 'Booking Reference',
    issuedDate: 'Issued',
    primaryGuest: 'Primary Guest Details',
    accommodationDetails: 'Accommodation Details',
    checkInDate: 'Check-In Date',
    checkOutDate: 'Check-Out Date',
    stayDuration: 'Stay Duration',
    occupancy: 'Occupancy',
    paymentBreakdown: 'Payment & Financial Breakdown',
    totalPaid: 'Total Amount Paid',
    totalPayable: 'Total Amount Payable',
    instantCheckInQr: 'Instant Check-In QR Verification',
    presentQrNotice: 'Present this physical voucher or digital QR code at the resort front desk upon arrival for priority check-in.',
    luxeStayVerified: 'LuxeStay Verified',
    guaranteedBooking: '100% Guaranteed Booking',
    needHelp: 'Need help? 24/7 Concierge:',
    printVoucher: 'Print / Save PDF Voucher',

    // Auth & Accounts
    welcomeBack: 'Welcome Back',
    createAccount: 'Create LuxeStay Account',
    customerAccount: 'Customer Account',
    partnerPortal: 'Partner Portal',
    guestAccount: 'Guest Account',
    fullNameLabel: 'FULL NAME *',
    emailLabel: 'EMAIL ADDRESS *',
    passwordLabel: 'PASSWORD *',
    forgotPassword: 'Forgot Password?',
    continueGoogle: 'Continue with Google',
    signUpGoogle: 'Sign Up with Google',
    adminDemo: '⚡ 1-Click Super Admin Demo Login',
    managerDemo: '⚡ 1-Click Hotel Partner Demo Login',
    customerDemo: '⚡ 1-Click VIP Customer Demo Login',
    noAccount: "Don't have an account in LuxeStay?",
    haveAccount: 'Already have an account in LuxeStay?',
    registerNow: 'REGISTER NOW',
    signInNow: 'SIGN IN NOW',
    profilePicture: 'Profile Picture',
    optionalUpload: 'Optional photo upload',

    // Footer & Trust
    footerBrandDesc: "The world's premier marketplace for luxury overwater bungalows, 5-star cliffside suites, traditional Japanese Ryokans, and high-altitude alpine chalets.",
    legalTrust: 'Legal & Trust',
    allRightsReserved: '© 2026 LuxeStay. All rights reserved. ThemeForest Commercial License Item.'
  },

  BN: {
    // Nav & General
    home: 'হোম',
    hotels: 'হোটেলসমূহ',
    offers: 'অফারসমূহ',
    gallery: 'গ্যালারি',
    contact: 'যোগাযোগ',
    pages: 'পেজসমূহ',
    about: 'আমাদের সম্পর্কে',
    blog: 'ট্রাভেল ব্লগ',
    faq: 'সাহায্য ও প্রশ্নাবলী',
    terms: 'শর্তাবলী ও গোপনীয়তা',
    termsOfService: 'ব্যবহারের শর্তাবলী',
    privacyPolicy: 'গোপনীয়তা নীতি',
    signIn: 'সাইন ইন',
    register: 'রেজিস্টার',
    logout: 'লগআউট',
    publicPages: 'পাবলিক পেজসমূহ',
    fullCatalog: 'সম্পূর্ণ ক্যাটালগ',
    customerPortals: 'গ্রাহক ও পোর্টাল',
    customerDashboard: 'কাস্টমার ড্যাশবোর্ড',
    partnerDashboard: 'হোটেল ম্যানেজার ড্যাশবোর্ড',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    myBookings: 'আমার বুকিং সমূহ',
    savedWishlist: 'সংরক্ষিত পছন্দের তালিকা',
    customerProfile: 'প্রোফাইল সেটিংস',
    listYourProperty: 'হোটেল বা রিসোর্ট যুক্ত করুন',
    notifications: 'নোটিফিকেশন',
    allCaughtUp: 'কোনো নতুন নোটিফিকেশন নেই',
    markAllRead: 'সবগুলো পড়া হয়েছে চিহ্নিত করুন',
    noNotifications: 'কোনো নোটিফিকেশন নেই',
    noNotifSub: 'আপনার সব নোটিফিকেশন আপডেট রয়েছে!',
    viewDashboard: 'ড্যাশবোর্ড দেখুন',
    exploreOffers: 'অফারগুলো দেখুন',
    unreadAlerts: 'টি অপঠিত নোটিফিকেশন',
    alerts: 'লাক্সস্টে অ্যালার্ট',

    // Hero & Search
    heroTitle: 'বুক করুন ওভারওয়াটার ভিলা, ক্যালডেরা সুইট এবং স্কি ক্যালেট',
    heroSub: 'তাৎক্ষণিক কিউআর ডিজিটাল ভাউচার, কোনো লুকানো ফি ছাড়াই সেরা মূল্যে বিশ্বের ৫-স্টার লাক্সারি রিসোর্ট বুক করুন।',
    searchPlaceholder: 'আপনার পরবর্তী গন্তব্য কোথায়? (যেমন: সান্তোরিনি, মালদ্বীপ...)',
    searchButton: 'লাক্সারি হোটেল খুঁজুন',
    searchPropertyPlaceholder: 'যেমন: রিসোর্ট, ভিলা, সান্তোরিনি...',
    allDestinations: 'সমস্ত গন্তব্যসমূহ',
    allTypes: 'সমস্ত লাক্সারি ক্যাটাগরি',
    propertyType: 'প্রোপার্টি টাইপ',
    guests: 'অতিথি সংখ্যা',
    dates: 'চেক-ইন / চেক-আউট',
    checkIn: 'চেক-ইন',
    checkOut: 'চেক-আউট',
    whereToNext: 'আপনার পরবর্তী গন্তব্য কোথায়?',
    guestCount: 'অতিথি ও রুম সংখ্যা',
    searchNow: 'এখনই খুঁজুন',

    // Categories
    allSuites: 'সমস্ত সুইটসমূহ',
    overwaterVillas: 'ওভারওয়াটার ভিলা',
    cliffsideResorts: 'ক্লিফসাইড রিসোর্ট',
    citySkyTowers: 'সিটি স্কাই টাওয়ার',
    zenRyokans: 'জাপানিজ রিয়োকান',
    skiChalets: 'স্কি ক্যালেট',
    resortSpas: 'রিসোর্ট ও স্পা',

    // Hotel Cards & Badges
    featuredSuites: 'পছন্দসই সেরা লাক্সারি সুইটসমূহ',
    curatedPortfolio: 'নির্বাচিত লাক্সারি পোর্টফোলিও',
    viewSuite: 'সুইট দেখুন',
    bookNow: 'বুক করুন',
    reserveSuite: 'রিজার্ভ করুন',
    perNight: 'রাত',
    nightlyRate: 'প্রতি রাতের মূল্য (ট্যাক্সসহ)',
    promoBanner: 'বিশেষ অফার: ২০% ছাড় পেতে SUMMER20 কোডটি ব্যবহার করুন!',
    freeBreakfast: 'ফ্রি বুফে প্রাতরাশ অন্তর্ভুক্ত',
    freeCancellation: 'বিনামূল্যে বুকিং বাতিল',
    qrVoucher: 'তাৎক্ষণিক কিউআর ডিজিটাল ভাউচার',
    ourGallery: 'আমাদের গ্যালারি',
    gallerySub: 'প্রাইভেট স্যুট, সুস্বাদু ডাইনিং ও সি-বীচের প্রশান্তিতে হারিয়ে যান',
    destinations: 'জনপ্রিয় গন্তব্যসমূহ',
    globalDestinations: 'গ্লোবাল ট্রাভেল ডেসটিনেশন',
    exploreWorld: 'বিশ্বের সেরা গন্তব্যসমূহ ঘুরে দেখুন',
    properties: 'টি প্রোপার্টি',
    explore: 'এক্সপ্লোর করুন',
    verifiedGuest: '১০০% যাচাইকৃত লাক্সারি স্টে',
    verifiedSub: 'প্রতিটি হোটেল আমাদের ৫০-পয়েন্ট লাক্সারি ইন্সপেকশন পার হয়ে যুক্ত হয়।',
    bestRate: 'সেরা মূল্যের গ্যারান্টি',
    bestRateSub: 'সরাসরি পার্টনার সংযোগের কারণে কোনো হিডেন চার্জ ছাড়াই বুকিং সুবিধা।',
    concierge: '২৪/৭ ডেডিকেটেড কনসিয়ার্জ সেবা',
    conciergeSub: 'ব্যক্তিগত এয়ারপোর্ট ভিআইপি শাটল ও মিশেলিন ডাইনিং রিজার্ভেশন সুবিধা।',
    guestExperiences: 'যাচাইকৃত গেস্ট অভিজ্ঞতা',
    lovedByTravelers: 'পর্যটকদের প্রিয় আন্তর্জাতিক পছন্দ',
    superb: 'চমৎকার',
    reviews: 'টি রিভিউ',
    allPhotos: 'সমস্ত ছবি',
    hotelGrounds: 'হোটেল ও প্রাঙ্গণ',
    roomsSuites: 'রুম ও সুইটসমূহ',
    fineDining: 'ফাইন ডাইনিং',
    spaWellness: 'স্পা ও ওয়েলনেস',
    viewMore: 'আরো দেখুন',
    unlockDiscount: 'আপনার পরবর্তী ট্রিপে ২০% ছাড় উপভোগ করুন',
    exclusivePromo: 'এক্সক্লুসিভ প্রমো ভাউচার',
    viewPromos: 'সমস্ত প্রমো দেখুন',
    spotlightTitle: 'স্পটলাইট লাক্সারি ডিলস',
    spotlightSub: 'সীমিত সময়ের বিশেষ মূল্য ও ভিআইপি সুবিধাসহ নির্বাচিত প্রিমিয়াম ভিলা',
    flashSale: 'ফ্ল্যাশ সেল',

    // Catalog & Filters
    filterTitle: 'ফিল্টার নির্বাচন',
    resetFilters: 'রিসেট',
    maxPrice: 'সর্বোচ্চ মূল্য / রাত',
    anyPrice: 'যেকোনো মূল্য',
    guestRating: 'গেস্ট রেটিং',
    anyRating: 'যেকোনো রেটিং',
    exceptional: '৪.৮★ ও ওপরে (ব্যতিক্রমী)',
    superbRating: '৪.৫★ ও ওপরে (চমৎকার)',
    veryGood: '৪.০★ ও ওপরে (খুব ভালো)',
    amenities: 'বিশেষ সুযোগ-সুবিধা',
    suitesFound: 'টি সুইট পাওয়া গেছে',
    sortBy: 'সাজান:',
    topRated: 'সর্বোচ্চ রেটিংপ্রাপ্ত',
    priceLowHigh: 'মূল্য: কম থেকে বেশি',
    priceHighLow: 'মূল্য: বেশি থেকে কম',
    listView: 'লিস্ট ভিউ',
    gridView: 'গ্রিড ভিউ',
    noHotelsFound: 'আপনার নির্বাচিত ফিল্টারে কোনো হোটেল পাওয়া যায়নি।',
    clearFilters: 'ফিল্টার ক্লিয়ার করুন',

    // Amenities
    infinityPool: 'ইনফিনিটি পুল',
    privateBeach: 'প্রাইভেট বিচ',
    luxurySpa: 'লাক্সারি স্পা',
    freeWifi: 'ফ্রি ওয়াই-ফাই',
    butlerService: 'পার্সোনাল বাটলার সার্ভিস',
    helipadAccess: 'হেলিপ্যাড সুবিধা',
    michelinDining: 'মিশেলিন ডাইনিং',
    skiInSkiOut: 'স্কি-ইন স্কি-আউট',
    privateJacuzzi: 'প্রাইভেট জাকুজি',
    airportShuttle: 'ভিআইপি এয়ারপোর্ট শাটল',

    // Detail & Rooms
    roomDetails: 'রুম ও সুইট বিবরণ',
    sleeps: 'ধারণক্ষমতা',
    sqFt: 'বর্গফুট',
    roomCapacity: 'সর্বোচ্চ অতিথি',
    diningPackages: 'খাবার ও ডাইনিং প্যাকেজ',
    curatedAddons: 'অতিরিক্ত প্রিমিয়াম সেবা',
    stayDates: 'বুকিং তারিখ ও অতিথি',
    proceedCheckout: 'চেকআউটে যান',
    roomReservedNotice: 'নির্বাচিত তারিখে এই রুমটি বুকড রয়েছে',

    // Voucher & Receipt
    officialVoucher: 'অফিসিয়াল স্টে ভাউচার ও পেমেন্ট রিসিট',
    verifiedAndPaid: 'যাচাইকৃত ও পরিশোধিত',
    holdGuaranteed: 'গ্যারান্টিড হোল্ড • চেক-ইনে পরিশোধ',
    bookingReference: 'বুকিং রেফারেন্স আইডি',
    issuedDate: 'ইস্যুর তারিখ',
    primaryGuest: 'অতিথির বিবরণ',
    accommodationDetails: 'হোটেল ও স্যুট বিবরণ',
    checkInDate: 'চেক-ইন তারিখ',
    checkOutDate: 'চেক-আউট তারিখ',
    stayDuration: 'অবস্থানের সময়কাল',
    occupancy: 'অতিথির সংখ্যা',
    paymentBreakdown: 'পেমেন্ট ও ভাউচার বিবরণ',
    totalPaid: 'পরিশোধিত মোট অর্থ',
    totalPayable: 'পরিশোধযোগ্য মোট অর্থ',
    instantCheckInQr: 'ইনস্ট্যান্ট চেক-ইন কিউআর কোড',
    presentQrNotice: 'অগ্রাধিকার ভিত্তিতে চেক-ইন পেতে হোটেলের ফ্রন্ট ডেস্কে এই ভাউচার বা ডিজিটাল কিউআর কোডটি দেখান।',
    luxeStayVerified: 'লাক্সস্টে ভেরিফাইড',
    guaranteedBooking: '১০০% নিশ্চিত বুকিং',
    needHelp: 'সাহায্য প্রয়োজন? ২৪/৭ কনসিয়ার্জ:',
    printVoucher: 'প্রিন্ট / PDF ভাউচার সংরক্ষণ',

    // Auth & Accounts
    welcomeBack: 'পুনরায় স্বাগতম',
    createAccount: 'লাক্সস্টে অ্যাকাউন্ট তৈরি করুন',
    customerAccount: 'কাস্টমার অ্যাকাউন্ট',
    partnerPortal: 'পার্টনার পোর্টাল',
    guestAccount: 'গেস্ট অ্যাকাউন্ট',
    fullNameLabel: 'সম্পূর্ণ নাম *',
    emailLabel: 'ইমেইল অ্যাড্রেস *',
    passwordLabel: 'পাসওয়ার্ড *',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    continueGoogle: 'গুগল দিয়ে সাইন ইন',
    signUpGoogle: 'গুগল দিয়ে রেজিস্টার',
    adminDemo: '⚡ ১-ক্লিকে সুপার অ্যাডমিন ডেমো লগইন',
    managerDemo: '⚡ ১-ক্লিকে হোটেল পার্টনার ডেমো লগইন',
    customerDemo: '⚡ ১-ক্লিকে ভিআইপি কাস্টমার ডেমো লগইন',
    noAccount: 'লাক্সস্টে-তে এখনও অ্যাকাউন্ট নেই?',
    haveAccount: 'ইতিমধ্যেই লাক্সস্টে অ্যাকাউন্ট আছে?',
    registerNow: 'এখনই রেজিস্টার করুন',
    signInNow: 'এখনই সাইন ইন করুন',
    profilePicture: 'প্রোফাইল ছবি',
    optionalUpload: 'ঐচ্ছিক ছবি আপলোড',

    // Footer & Trust
    footerBrandDesc: 'বিশ্বের শীর্ষস্থানীয় ওভারওয়াটার বাংলো, ৫-স্টার ক্লিফসাইড রিসোর্ট, জাপানিজ রিয়োকান এবং আলপাইন শ্যালে বুকিং প্ল্যাটফর্ম।',
    legalTrust: 'আইন ও নিরাপত্তা',
    allRightsReserved: '© ২০২৬ লাক্সস্টে। সর্বস্বত্ব সংরক্ষিত।'
  },

  ES: {
    // Nav & General
    home: 'Inicio',
    hotels: 'Hoteles',
    offers: 'Ofertas',
    gallery: 'Galería',
    contact: 'Contacto',
    pages: 'Páginas',
    about: 'Sobre Nosotros',
    blog: 'Blog de Viajes',
    faq: 'Ayuda y Preguntas',
    terms: 'Términos y Privacidad',
    termsOfService: 'Términos de Servicio',
    privacyPolicy: 'Política de Privacidad',
    signIn: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    publicPages: 'Páginas Públicas',
    fullCatalog: 'Catálogo Completo',
    customerPortals: 'Clientes y Portales',
    customerDashboard: 'Panel de Cliente',
    partnerDashboard: 'Panel de Gerente',
    adminDashboard: 'Panel de Administrador',
    myBookings: 'Mis Reservas',
    savedWishlist: 'Lista de Deseos',
    customerProfile: 'Configuración de Perfil',
    listYourProperty: 'Publica tu Propiedad',
    notifications: 'Notificaciones',
    allCaughtUp: 'Todo al día',
    markAllRead: 'Marcar todo leído',
    noNotifications: 'Sin notificaciones',
    noNotifSub: '¡Estás completamente al día por ahora!',
    viewDashboard: 'Ver Panel',
    exploreOffers: 'Explorar Ofertas',
    unreadAlerts: 'alertas no leídas',
    alerts: 'Alertas LuxeStay',

    // Hero & Search
    heroTitle: 'Reserve Villas Sobre el Agua, Suites Caldera y Chalets de Esquí',
    heroSub: 'Comprobantes QR instantáneos, cero cargos ocultos y los mejores precios garantizados en santuarios de 5 estrellas en todo el mundo.',
    searchPlaceholder: '¿A dónde viajas? (ej. Santorini, Maldivas, Tokio...)',
    searchButton: 'Buscar Estancias de Lujo',
    searchPropertyPlaceholder: 'ej. Resort, Villa, Santorini...',
    allDestinations: 'Todos los Destinos',
    allTypes: 'Todos los Tipos de Lujo',
    propertyType: 'Tipo de Propiedad',
    guests: 'Huéspedes',
    dates: 'Entrada / Salida',
    checkIn: 'Entrada',
    checkOut: 'Salida',
    whereToNext: '¿A dónde viajas?',
    guestCount: 'Huéspedes y Habitaciones',
    searchNow: 'Buscar Ahora',

    // Categories
    allSuites: 'Todas las Suites',
    overwaterVillas: 'Villas Sobre el Agua',
    cliffsideResorts: 'Resorts en Acantilados',
    citySkyTowers: 'Torres Urbanas de Lujo',
    zenRyokans: 'Ryokans Zen',
    skiChalets: 'Chalets de Esquí',
    resortSpas: 'Resorts y Spas',

    // Hotel Cards & Badges
    featuredSuites: 'Suites Exclusivas Seleccionadas',
    curatedPortfolio: 'Portafolio Exclusivo de Lujo',
    viewSuite: 'Ver Suite',
    bookNow: 'Reservar Ahora',
    reserveSuite: 'Reservar Suite',
    perNight: 'noche',
    nightlyRate: 'Tarifa por Noche (Impuestos Incluidos)',
    promoBanner: '¡PROMO ESPECIAL: Usa SUMMER20 para un 20% de descuento!',
    freeBreakfast: 'Desayuno Gourmet Incluido',
    freeCancellation: 'Cancelación Gratuita',
    qrVoucher: 'Bono QR Digital Instantáneo',
    ourGallery: 'Nuestra Galería',
    gallerySub: 'Sumérjase en santuarios privados, alta cocina y tranquilidad frente al mar',
    destinations: 'Destinos Populares',
    globalDestinations: 'Destinos Globales',
    exploreWorld: 'Explora Destinos Mundiales',
    properties: 'Propiedades',
    explore: 'Explorar',
    verifiedGuest: 'Estancias 100% Verificadas',
    verifiedSub: 'Cada propiedad pasa nuestra inspección de 50 puntos de lujo asegurando total privacidad.',
    bestRate: 'Mejor Tarifa Garantizada',
    bestRateSub: 'Sin comisiones ocultas con emisión digital instantánea de comprobante.',
    concierge: 'Conserje Dedicado 24/7',
    conciergeSub: 'Traslados VIP y reservas de degustación Michelin a su servicio.',
    guestExperiences: 'Experiencias de Huéspedes',
    lovedByTravelers: 'Amado por Viajeros Exigentes',
    superb: 'Excelente',
    reviews: 'reseñas',
    allPhotos: 'TODAS LAS FOTOS',
    hotelGrounds: 'HOTEL Y JARDINES',
    roomsSuites: 'HABITACIONES Y SUITES',
    fineDining: 'ALTA COCINA',
    spaWellness: 'SPA Y BIENESTAR',
    viewMore: 'VER MÁS',
    unlockDiscount: 'Desbloquee 20% de Descuento en su Próxima Escapada',
    exclusivePromo: 'Cupón de Promoción Exclusivo',
    viewPromos: 'Ver Todas las Promos',
    spotlightTitle: 'Ofertas Destacadas de Lujo',
    spotlightSub: 'Villas seleccionadas con tarifas promocionales por tiempo limitado y ventajas VIP',
    flashSale: 'VENTA FLASH',

    // Catalog & Filters
    filterTitle: 'Filtros de Búsqueda',
    resetFilters: 'Restablecer',
    maxPrice: 'Precio Máx. / Noche',
    anyPrice: 'Cualquier Precio',
    guestRating: 'Calificación',
    anyRating: 'Cualquier Calificación',
    exceptional: '4.8★ y Más (Excepcional)',
    superbRating: '4.5★ y Más (Excelente)',
    veryGood: '4.0★ y Más (Muy Bueno)',
    amenities: 'Servicios Exclusivos',
    suitesFound: 'Suites Encontradas',
    sortBy: 'Ordenar por:',
    topRated: 'Mejor Calificación',
    priceLowHigh: 'Precio: Menor a Mayor',
    priceHighLow: 'Precio: Mayor a Menor',
    listView: 'Vista de Lista',
    gridView: 'Vista de Cuadrícula',
    noHotelsFound: 'Ninguna suite coincide con sus filtros actuales.',
    clearFilters: 'Borrar Filtros',

    // Amenities
    infinityPool: 'Piscina Infinita',
    privateBeach: 'Playa Privada',
    luxurySpa: 'Spa de Lujo',
    freeWifi: 'Wi-Fi Gratis',
    butlerService: 'Servicio de Mayordomo',
    helipadAccess: 'Helipuerto',
    michelinDining: 'Comedor Michelin',
    skiInSkiOut: 'Acceso a Pistas de Esquí',
    privateJacuzzi: 'Jacuzzi Privado',
    airportShuttle: 'Traslado VIP al Aeropuerto',

    // Detail & Rooms
    roomDetails: 'Detalles de la Suite',
    sleeps: 'Capacidad',
    sqFt: 'pies cuadrados',
    roomCapacity: 'Capacidad Máxima',
    diningPackages: 'Paquetes de Comida y Gastronomía',
    curatedAddons: 'Servicios Extra de Lujo',
    stayDates: 'Fechas y Huéspedes',
    proceedCheckout: 'Continuar al Pago',
    roomReservedNotice: 'HABITACIÓN RESERVADA PARA ESTAS FECHAS',

    // Voucher & Receipt
    officialVoucher: 'Comprobante Oficial de Estancia y Recibo',
    verifiedAndPaid: 'VERIFICADO Y PAGADO',
    holdGuaranteed: 'RESERVA GARANTIZADA • PAGO AL LLEGAR',
    bookingReference: 'Referencia de Reserva',
    issuedDate: 'Emitido',
    primaryGuest: 'Datos del Huésped Principal',
    accommodationDetails: 'Detalles del Alojamiento',
    checkInDate: 'Fecha de Entrada',
    checkOutDate: 'Fecha de Salida',
    stayDuration: 'Duración',
    occupancy: 'Ocupación',
    paymentBreakdown: 'Desglose Financiero',
    totalPaid: 'Total Pagado',
    totalPayable: 'Total a Pagar',
    instantCheckInQr: 'Verificación QR para Check-In Rápido',
    presentQrNotice: 'Presente este comprobante o código QR en la recepción para check-in prioritario.',
    luxeStayVerified: 'Verificado LuxeStay',
    guaranteedBooking: 'Reserva 100% Garantizada',
    needHelp: '¿Necesita ayuda? Conserje 24/7:',
    printVoucher: 'Imprimir / Guardar en PDF',

    // Auth & Accounts
    welcomeBack: 'Bienvenido de Nuevo',
    createAccount: 'Crear Cuenta LuxeStay',
    customerAccount: 'Cuenta de Cliente',
    partnerPortal: 'Portal de Socios',
    guestAccount: 'Cuenta de Huésped',
    fullNameLabel: 'NOMBRE COMPLETO *',
    emailLabel: 'CORREO ELECTRÓNICO *',
    passwordLabel: 'CONTRASEÑA *',
    forgotPassword: '¿Olvidó su contraseña?',
    continueGoogle: 'Continuar con Google',
    signUpGoogle: 'Registrarse con Google',
    adminDemo: '⚡ Demo Super Admin en 1 Clic',
    managerDemo: '⚡ Demo Socio Hotelero en 1 Clic',
    customerDemo: '⚡ Demo Cliente VIP en 1 Clic',
    noAccount: '¿No tiene una cuenta en LuxeStay?',
    haveAccount: '¿Ya tiene una cuenta en LuxeStay?',
    registerNow: 'REGISTRARSE AHORA',
    signInNow: 'INICIAR SESIÓN AHORA',
    profilePicture: 'Foto de Perfil',
    optionalUpload: 'Subida de foto opcional',

    // Footer & Trust
    footerBrandDesc: 'El marketplace líder mundial de bungalows sobre el agua, suites en acantilados de 5 estrellas, Ryokans tradicionales y chalets alpinos.',
    legalTrust: 'Legal y Confianza',
    allRightsReserved: '© 2026 LuxeStay. Todos los derechos reservados.'
  },

  FR: {
    // Nav & General
    home: 'Accueil',
    hotels: 'Hôtels',
    offers: 'Offres',
    gallery: 'Galerie',
    contact: 'Contact',
    pages: 'Pages',
    about: 'À Propos',
    blog: 'Blog Voyage',
    faq: 'Aide & FAQ',
    terms: 'Conditions & Confidentialité',
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: 'Politique de Confidentialité',
    signIn: 'Connexion',
    register: 'Inscription',
    logout: 'Déconnexion',
    publicPages: 'Pages Publiques',
    fullCatalog: 'Catalogue Complet',
    customerPortals: 'Clients & Portails',
    customerDashboard: 'Tableau de Bord Client',
    partnerDashboard: 'Tableau de Bord Gestionnaire',
    adminDashboard: 'Tableau de Bord Admin',
    myBookings: 'Mes Réservations',
    savedWishlist: 'Favoris Enregistrés',
    customerProfile: 'Paramètres du Profil',
    listYourProperty: 'Inscrire un Établissement',
    notifications: 'Notifications',
    allCaughtUp: 'Tout est à jour',
    markAllRead: 'Tout marquer comme lu',
    noNotifications: 'Aucune notification',
    noNotifSub: 'Vous êtes totalement à jour !',
    viewDashboard: 'Voir le Tableau de Bord',
    exploreOffers: 'Découvrir les Offres',
    unreadAlerts: 'alertes non lues',
    alerts: 'Alertes LuxeStay',

    // Hero & Search
    heroTitle: 'Réservez Villas sur Pilotis, Suites Caldeira & Chalets de Ski',
    heroSub: 'Bons de séjour QR instantanés, aucun frais caché et meilleurs prix garantis dans des sanctuaires 5 étoiles à travers le monde.',
    searchPlaceholder: 'Votre prochaine destination ? (ex. Santorin, Maldives, Tokyo...)',
    searchButton: 'Rechercher des Séjours de Luxe',
    searchPropertyPlaceholder: 'ex. Resort, Villa, Santorin...',
    allDestinations: 'Toutes les Destinations',
    allTypes: 'Tous les Types de Luxe',
    propertyType: "Type d'Établissement",
    guests: 'Voyageurs',
    dates: 'Arrivée / Départ',
    checkIn: 'Arrivée',
    checkOut: 'Départ',
    whereToNext: 'Votre prochaine destination ?',
    guestCount: 'Voyageurs & Chambres',
    searchNow: 'Rechercher',

    // Categories
    allSuites: 'Toutes les Suites',
    overwaterVillas: 'Villas sur Pilotis',
    cliffsideResorts: 'Resorts à Flanc de Falaise',
    citySkyTowers: 'Tours Urbaines de Prestige',
    zenRyokans: 'Ryokans Japonais Zen',
    skiChalets: 'Chalets Alpins',
    resortSpas: 'Resorts & Spas',

    // Hotel Cards & Badges
    featuredSuites: "Sélection d'Exception",
    curatedPortfolio: 'Portfolio de Luxe Trié sur le Volet',
    viewSuite: 'Voir la Suite',
    bookNow: 'Réserver',
    reserveSuite: 'Réserver la Suite',
    perNight: 'nuit',
    nightlyRate: 'Tarif par Nuit (Taxes Incluses)',
    promoBanner: 'PROMO SPÉCIALE : Utilisez SUMMER20 pour -20% sur les villas !',
    freeBreakfast: 'Petit-déjeuner Gourmet Inclus',
    freeCancellation: 'Annulation Gratuite',
    qrVoucher: 'Bon QR Numérique Instantané',
    ourGallery: 'Notre Galerie',
    gallerySub: 'Plongez dans des havres de paix privés, haute gastronomie et sérénité en bord de mer',
    destinations: 'Destinations Populaires',
    globalDestinations: 'Destinations Mondiales',
    exploreWorld: 'Explorer les Destinations Mondiales',
    properties: 'Propriétés',
    explore: 'Explorer',
    verifiedGuest: 'Séjours 100% Vérifiés',
    verifiedSub: 'Chaque propriété réussit notre inspection en 50 points garantissant intimité et service majordome.',
    bestRate: 'Garantie du Meilleur Tarif',
    bestRateSub: 'Intégration directe sans frais cachés avec émission instantanée de bon.',
    concierge: 'Conciergerie Dédiée 24/7',
    conciergeSub: 'Navette VIP aéroport et réservations dégustation Michelin à votre service.',
    guestExperiences: 'Avis Clients Vérifiés',
    lovedByTravelers: 'Prisé par les Voyageurs Exigeants',
    superb: 'Superbe',
    reviews: 'avis',
    allPhotos: 'TOUTES LES PHOTOS',
    hotelGrounds: 'HÔTEL & DOMAINE',
    roomsSuites: 'CHAMBRES & SUITES',
    fineDining: 'GASTRONOMIE',
    spaWellness: 'SPA & BIEN-ÊTRE',
    viewMore: 'VOIR PLUS',
    unlockDiscount: 'Obtenez 20% de Réduction sur Votre Prochaine Évasion',
    exclusivePromo: 'Bon Promo Exclusif',
    viewPromos: 'Voir Toutes les Offres',
    spotlightTitle: 'Offres de Luxe à la Une',
    spotlightSub: 'Villas d’exception avec tarifs promotionnels limités et avantages VIP inclus',
    flashSale: 'VENTE FLASH',

    // Catalog & Filters
    filterTitle: 'Sélection des Filtres',
    resetFilters: 'Réinitialiser',
    maxPrice: 'Prix Max. / Nuit',
    anyPrice: 'Tous les Prix',
    guestRating: 'Note des Clients',
    anyRating: 'Toutes les Notes',
    exceptional: '4.8★ & Plus (Exceptionnel)',
    superbRating: '4.5★ & Plus (Superbe)',
    veryGood: '4.0★ & Plus (Très Bon)',
    amenities: 'Équipements de Prestige',
    suitesFound: 'Suites Trouvées',
    sortBy: 'Trier par :',
    topRated: 'Meilleures Notes',
    priceLowHigh: 'Prix : Croissant',
    priceHighLow: 'Prix : Décroissant',
    listView: 'Vue Liste',
    gridView: 'Vue Grille',
    noHotelsFound: 'Aucune suite ne correspond à vos filtres actuels.',
    clearFilters: 'Effacer les Filtres',

    // Amenities
    infinityPool: 'Piscine à Débordement',
    privateBeach: 'Plage Privée',
    luxurySpa: 'Spa de Luxe',
    freeWifi: 'Wi-Fi Gratuit',
    butlerService: 'Service de Majordome',
    helipadAccess: 'Héliport',
    michelinDining: 'Table Étoilée Michelin',
    skiInSkiOut: 'Accès Direct aux Pistes',
    privateJacuzzi: 'Jacuzzi Privatif',
    airportShuttle: 'Navette VIP Aéroport',

    // Detail & Rooms
    roomDetails: 'Détails de la Suite',
    sleeps: 'Capacité',
    sqFt: 'm²',
    roomCapacity: 'Capacité Maximale',
    diningPackages: 'Formules Repas & Restauration',
    curatedAddons: 'Prestations de Luxe en Option',
    stayDates: 'Dates de Séjour & Voyageurs',
    proceedCheckout: 'Passer au Paiement',
    roomReservedNotice: 'CHAMBRE RÉSERVÉE POUR CES DATES',

    // Voucher & Receipt
    officialVoucher: 'Bon de Séjour Officiel & Reçu de Réservation',
    verifiedAndPaid: 'VÉRIFIÉ & RÉGLÉ',
    holdGuaranteed: 'RÉSERVATION GARANTIE • PAIEMENT SUR PLACE',
    bookingReference: 'Référence de Réservation',
    issuedDate: 'Délivré le',
    primaryGuest: 'Détails du Client Principal',
    accommodationDetails: "Détails de l'Hébergement",
    checkInDate: "Date d'Arrivée",
    checkOutDate: 'Date de Départ',
    stayDuration: 'Durée du Séjour',
    occupancy: 'Occupation',
    paymentBreakdown: 'Détail Financier & Paiement',
    totalPaid: 'Montant Total Réglé',
    totalPayable: 'Montant Total à Régler',
    instantCheckInQr: 'Vérification QR pour Enregistrement Immédiat',
    presentQrNotice: "Présentez ce bon ou QR code à la réception de l'hôtel dès votre arrivée.",
    luxeStayVerified: 'Vérifié LuxeStay',
    guaranteedBooking: 'Réservation 100% Garantie',
    needHelp: 'Besoin d’aide ? Conciergerie 24/7 :',
    printVoucher: 'Imprimer / Enregistrer en PDF',

    // Auth & Accounts
    welcomeBack: 'Bon Retour',
    createAccount: 'Créer un Compte LuxeStay',
    customerAccount: 'Compte Client',
    partnerPortal: 'Portail Partenaire',
    guestAccount: 'Compte Invité',
    fullNameLabel: 'NOM COMPLET *',
    emailLabel: 'ADRESSE E-MAIL *',
    passwordLabel: 'MOT DE PASSE *',
    forgotPassword: 'Mot de passe oublié ?',
    continueGoogle: 'Continuer avec Google',
    signUpGoogle: "S'inscrire avec Google",
    adminDemo: '⚡ Démo Super Admin en 1 Clic',
    managerDemo: '⚡ Démo Partenaire Hôtelier en 1 Clic',
    customerDemo: '⚡ Démo Client VIP en 1 Clic',
    noAccount: "Vous n'avez pas de compte LuxeStay ?",
    haveAccount: 'Vous avez déjà un compte LuxeStay ?',
    registerNow: "S'INSCRIRE MAINTENANT",
    signInNow: 'SE CONNECTER',
    profilePicture: 'Photo de Profil',
    optionalUpload: 'Photo optionnelle',

    // Footer & Trust
    footerBrandDesc: 'La première plateforme mondiale de villas sur pilotis, suites 5 étoiles à flanc de falaise, Ryokans japonais et chalets alpins.',
    legalTrust: 'Confiance & Légalité',
    allRightsReserved: '© 2026 LuxeStay. Tous droits réservés.'
  },

  AR: {
    // Nav & General
    home: 'الرئيسية',
    hotels: 'الفنادق',
    offers: 'العروض',
    gallery: 'المعرض',
    contact: 'اتصل بنا',
    pages: 'الصفحات',
    about: 'من نحن',
    blog: 'مدونة السفر',
    faq: 'المساعدة والأسئلة',
    terms: 'الشروط والخصوصية',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    signIn: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    publicPages: 'الصفحات العامة',
    fullCatalog: 'الكتالوج الكامل',
    customerPortals: 'العملاء والبوابات',
    customerDashboard: 'لوحة تحكم العميل',
    partnerDashboard: 'لوحة تحكم المدير',
    adminDashboard: 'لوحة تحكم المشرف',
    myBookings: 'حجوزاتي',
    savedWishlist: 'قائمة الرغبات المحفوظة',
    customerProfile: 'إعدادات الملف الشخصي',
    listYourProperty: 'أضف عقارك الفاخر',
    notifications: 'الإشعارات',
    allCaughtUp: 'لا توجد إشعارات جديدة',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات',
    noNotifSub: 'أنت مطلع على كل شيء حالياً!',
    viewDashboard: 'عرض لوحة التحكم',
    exploreOffers: 'استكشاف العروض',
    unreadAlerts: 'تنبيهات غير مقروءة',
    alerts: 'تنبيهات لوكس ستيه',

    // Hero & Search
    heroTitle: 'احجز فيلات فوق الماء وأجنحة كالديرا وشاليهات تزلج فاخرة',
    heroSub: 'قسائم إقامة إلكترونية فورية برمز QR وبدون أي رسوم خفية مع أفضل الأسعار المضمونة عالمياً.',
    searchPlaceholder: 'إلى أين وجهتك القادمة؟ (مثل: سانتوريني، المالديف، طوكيو...)',
    searchButton: 'بحث عن إقامات فاخرة',
    searchPropertyPlaceholder: 'مثل: منتجع، فيلا، سانتوريني...',
    allDestinations: 'جميع الوجهات',
    allTypes: 'جميع الفئات الفاخرة',
    propertyType: 'نوع العقار',
    guests: 'النزلاء',
    dates: 'تسجيل الوصول / المغادرة',
    checkIn: 'تسجيل الوصول',
    checkOut: 'تسجيل المغادرة',
    whereToNext: 'إلى أين وجهتك القادمة؟',
    guestCount: 'النزلاء والغرف',
    searchNow: 'ابحث الآن',

    // Categories
    allSuites: 'جميع الأجنحة',
    overwaterVillas: 'فيلات فوق الماء',
    cliffsideResorts: 'منتجعات على المنحدرات',
    citySkyTowers: 'أبراج فاخرة في المدينة',
    zenRyokans: 'ريوكان ياباني أصيل',
    skiChalets: 'شاليهات تزلج',
    resortSpas: 'منتجعات وسبا',

    // Hotel Cards & Badges
    featuredSuites: 'أجنحة فاخرة مختارة بعناية',
    curatedPortfolio: 'محفظة الفخامة العالمية',
    viewSuite: 'عرض الجناح',
    bookNow: 'احجز الآن',
    reserveSuite: 'حجز الجناح',
    perNight: 'ليلة',
    nightlyRate: 'السعر لكل ليلة (شامل الضرائب)',
    promoBanner: 'عرض خاص: استخدم الرمز SUMMER20 للحصول على خصم 20%!',
    freeBreakfast: 'إفطار فاخر مشمول',
    freeCancellation: 'إلغاء مجاني',
    qrVoucher: 'قسيمة إقامة فورية برمز QR',
    ourGallery: 'معرض الصور',
    gallerySub: 'استمتع بالخصوصية التامة والمطاعم الفاخرة وإطلالات الشاطئ الساحرة',
    destinations: 'أشهر الوجهات',
    globalDestinations: 'وجهات سياحية عالمية',
    exploreWorld: 'استكشف وجهات العالم الفاخرة',
    properties: 'عقار',
    explore: 'استكشف',
    verifiedGuest: 'إقامات موثقة 100%',
    verifiedSub: 'كل عقار يجتاز فحص الجودة المكون من 50 نقطة لضمان أقصى درجات الخصوصية.',
    bestRate: 'ضمان أفضل سعر',
    bestRateSub: 'ربط مباشر بدون أي عمولات وسيط مع إصدار فوري لقسيمة الإقامة الرقمية.',
    concierge: 'خدمة كونسيرج 24/7',
    conciergeSub: 'خدمة نقل VIP من وإلى المطار وحجوزات مطاعم ميشلان تحت تصرفكم.',
    guestExperiences: 'تجارب النزلاء الموثقة',
    lovedByTravelers: 'مفضّل لدى النخبة من المسافرين',
    superb: 'ممتاز جداً',
    reviews: 'تقييم',
    allPhotos: 'جميع الصور',
    hotelGrounds: 'الفندق والمرافق',
    roomsSuites: 'الغرف والأجنحة',
    fineDining: 'المطاعم الفاخرة',
    spaWellness: 'السبا والعافية',
    viewMore: 'عرض المزيد',
    unlockDiscount: 'احصل على خصم 20% لرحلتك القادمة',
    exclusivePromo: 'قسيمة ترويجية حصرية',
    viewPromos: 'عرض جميع العروض',
    spotlightTitle: 'عروض الفخامة المميزة',
    spotlightSub: 'فيلات منتقاة بعناية مع أسعار ترويجية محدودة ومزايا كبار الشخصيات المجانية',
    flashSale: 'تخفيضات كبرى',

    // Catalog & Filters
    filterTitle: 'تصفية النتائج',
    resetFilters: 'إعادة ضبط',
    maxPrice: 'أعلى سعر / ليلة',
    anyPrice: 'أي سعر',
    guestRating: 'تقييم النزلاء',
    anyRating: 'أي تقييم',
    exceptional: '4.8★ فأكثر (استثنائي)',
    superbRating: '4.5★ فأكثر (ممتاز جداً)',
    veryGood: '4.0★ فأكثر (جيد جداً)',
    amenities: 'المرافق المميزة',
    suitesFound: 'أجنحة متوفرة',
    sortBy: 'ترتيب حسب:',
    topRated: 'الأعلى تقييماً',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    listView: 'عرض القائمة',
    gridView: 'عرض الشبكة',
    noHotelsFound: 'لا توجد أجنحة مطابقة لخيارات التصفية الحالية.',
    clearFilters: 'مسح جميع الفلاتر',

    // Amenities
    infinityPool: 'مسبح إنفينيتي',
    privateBeach: 'شاطئ خاص',
    luxurySpa: 'سبا فاخر',
    freeWifi: 'واي فاي مجاني',
    butlerService: 'خدمة كبير الخدم الخاص',
    helipadAccess: 'مهبط طائرات هليكوبتر',
    michelinDining: 'مطاعم ميشلان',
    skiInSkiOut: 'دخول مباشر لمسارات التزلج',
    privateJacuzzi: 'جاكوزي خاص',
    airportShuttle: 'توصيل VIP للمطار',

    // Detail & Rooms
    roomDetails: 'تفاصيل الجناح والغرفة',
    sleeps: 'يتسع لـ',
    sqFt: 'قدم مربع',
    roomCapacity: 'السعة القصوى',
    diningPackages: 'باقات الوجبات وتناول الطعام',
    curatedAddons: 'خدمات إضافية فاخرة',
    stayDates: 'تواريخ الإقامة والنزلاء',
    proceedCheckout: 'المتابعة للدفع',
    roomReservedNotice: 'الغرفة محجوزة لهذه التواريخ',

    // Voucher & Receipt
    officialVoucher: 'قسيمة الإقامة الرسمية وإيصال الدفع',
    verifiedAndPaid: 'موثق ومدفوع بالكامل',
    holdGuaranteed: 'حجز مضمون • الدفع عند الوصول',
    bookingReference: 'رقم مرجع الحجز',
    issuedDate: 'تاريخ الإصدار',
    primaryGuest: 'بيانات النزيل الأساسي',
    accommodationDetails: 'تفاصيل مكان الإقامة',
    checkInDate: 'تاريخ تسجيل الوصول',
    checkOutDate: 'تاريخ تسجيل المغادرة',
    stayDuration: 'مدة الإقامة',
    occupancy: 'عدد النزلاء',
    paymentBreakdown: 'التفاصيل المالية والدفع',
    totalPaid: 'المبلغ الإجمالي المدفوع',
    totalPayable: 'المبلغ الإجمالي المستحق',
    instantCheckInQr: 'رمز QR للتحقق السريع وتسجيل الوصول',
    presentQrNotice: 'يرجى إبراز هذه القسيمة أو رمز QR في مكتب الاستقبال لتسجيل الوصول الفوري.',
    luxeStayVerified: 'موثق من لوكس ستيه',
    guaranteedBooking: 'حجز مضمون 100%',
    needHelp: 'هل تحتاج مساعدة؟ الكونسيرج 24/7:',
    printVoucher: 'طباعة / حفظ كملف PDF',

    // Auth & Accounts
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب في لوكس ستيه',
    customerAccount: 'حساب عميل',
    partnerPortal: 'بوابة الشركاء',
    guestAccount: 'حساب زائر',
    fullNameLabel: 'الاسم الكامل *',
    emailLabel: 'البريد الإلكتروني *',
    passwordLabel: 'كلمة المرور *',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    continueGoogle: 'المتابعة عبر جوجل',
    signUpGoogle: 'إنشاء حساب عبر جوجل',
    adminDemo: '⚡ تسجيل دخول تجريبي للمشرف بنقرة واحدة',
    managerDemo: '⚡ تسجيل دخول تجريبي لمدير الفندق بنقرة واحدة',
    customerDemo: '⚡ تسجيل دخول تجريبي للعميل المميز بنقرة واحدة',
    noAccount: 'ليس لديك حساب في لوكس ستيه؟',
    haveAccount: 'هل لديك حساب بالفعل في لوكس ستيه؟',
    registerNow: 'سجل الآن',
    signInNow: 'سجل الدخول الآن',
    profilePicture: 'الصورة الشخصية',
    optionalUpload: 'رفع صورة اختياري',

    // Footer & Trust
    footerBrandDesc: 'المنصة العالمية الرائدة لحجز الأكواخ فوق الماء وأجنحة الجرف من فئة 5 نجوم ونزل الريوكان الياباني وشاليهات جبال الألب الفاخرة.',
    legalTrust: 'الأمان والقانون',
    allRightsReserved: '© 2026 لوكس ستيه. جميع الحقوق محفوظة.'
  },

  DE: {
    // Nav & General
    home: 'Startseite',
    hotels: 'Hotels',
    offers: 'Angebote',
    gallery: 'Galerie',
    contact: 'Kontakt',
    pages: 'Seiten',
    about: 'Über Uns',
    blog: 'Reiseblog',
    faq: 'Hilfe & FAQ',
    terms: 'AGB & Datenschutz',
    termsOfService: 'Nutzungsbedingungen',
    privacyPolicy: 'Datenschutzerklärung',
    signIn: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    publicPages: 'Öffentliche Seiten',
    fullCatalog: 'Vollständiger Katalog',
    customerPortals: 'Kunden & Portale',
    customerDashboard: 'Kunden-Dashboard',
    partnerDashboard: 'Manager-Dashboard',
    adminDashboard: 'Admin-Dashboard',
    myBookings: 'Meine Buchungen',
    savedWishlist: 'Gespeicherte Wunschliste',
    customerProfile: 'Profileinstellungen',
    listYourProperty: 'Unterkunft Inserieren',
    notifications: 'Benachrichtigungen',
    allCaughtUp: 'Alles auf dem neuesten Stand',
    markAllRead: 'Alle als gelesen markieren',
    noNotifications: 'Keine Benachrichtigungen',
    noNotifSub: 'Sie sind aktuell auf dem neuesten Stand!',
    viewDashboard: 'Dashboard Öffnen',
    exploreOffers: 'Angebote Erkunden',
    unreadAlerts: 'ungelesene Benachrichtigungen',
    alerts: 'LuxeStay Benachrichtigungen',

    // Hero & Search
    heroTitle: 'Buchen Sie Überwasservillen, Caldera-Suiten & Skichalets',
    heroSub: 'Sofortige digitale QR-Gutscheine, keine versteckten Gebühren und garantierte Bestpreise in 5-Sterne-Luxusresorts weltweit.',
    searchPlaceholder: 'Wohin soll Ihre nächste Reise gehen? (z.B. Santorin, Malediven, Tokio...)',
    searchButton: 'Luxusunterkünfte Suchen',
    searchPropertyPlaceholder: 'z.B. Resort, Villa, Santorin...',
    allDestinations: 'Alle Reiseziele',
    allTypes: 'Alle Luxus-Kategorien',
    propertyType: 'Unterkunftsart',
    guests: 'Gäste',
    dates: 'Anreise / Abreise',
    checkIn: 'Anreise',
    checkOut: 'Abreise',
    whereToNext: 'Wohin soll Ihre nächste Reise gehen?',
    guestCount: 'Gäste & Zimmer',
    searchNow: 'Jetzt Suchen',

    // Categories
    allSuites: 'Alle Suiten',
    overwaterVillas: 'Überwasservillen',
    cliffsideResorts: 'Klippen-Resorts',
    citySkyTowers: 'Stadt-Luxustürme',
    zenRyokans: 'Traditionelle Ryokans',
    skiChalets: 'Skichalets',
    resortSpas: 'Resorts & Spas',

    // Hotel Cards & Badges
    featuredSuites: 'Ausgewählte Luxussuiten',
    curatedPortfolio: 'Kuratierte Luxusauswahl',
    viewSuite: 'Suite Ansehen',
    bookNow: 'Jetzt Buchen',
    reserveSuite: 'Suite Reservieren',
    perNight: 'Nacht',
    nightlyRate: 'Preis pro Nacht (Inkl. Steuern)',
    promoBanner: 'SONDERAKTION: 20% Rabatt mit Code SUMMER20!',
    freeBreakfast: 'Gourmet-Frühstück Inklusive',
    freeCancellation: 'Kostenlose Stornierung',
    qrVoucher: 'Sofortiger QR-Gutschein',
    ourGallery: 'Unsere Galerie',
    gallerySub: 'Tauchen Sie ein in private Zufluchtsorte und feine Gastronomie',
    destinations: 'Beliebte Reiseziele',
    globalDestinations: 'Weltweite Reiseziele',
    exploreWorld: 'Entdecken Sie Weltweite Reiseziele',
    properties: 'Unterkünfte',
    explore: 'Entdecken',
    verifiedGuest: '100% Geprüfte Unterkünfte',
    verifiedSub: 'Jede Unterkunft besteht unsere 50-Punkte-Luxusprüfung.',
    bestRate: 'Bestpreisgarantie',
    bestRateSub: 'Direkte Partnerintegration ohne versteckte Gebühren.',
    concierge: '24/7 Concierge-Service',
    conciergeSub: 'Individueller VIP-Flughafentransfer zu Ihren Diensten.',
    guestExperiences: 'Verifizierte Gästebewertungen',
    lovedByTravelers: 'Beliebt bei Anspruchsvollen Reisenden',
    superb: 'Hervorragend',
    reviews: 'Bewertungen',
    allPhotos: 'ALLE FOTOS',
    hotelGrounds: 'HOTEL & ANLAGE',
    roomsSuites: 'ZIMMER & SUITEN',
    fineDining: 'GASTRONOMIE',
    spaWellness: 'SPA & WELLNESS',
    viewMore: 'MEHR ANSEHEN',
    unlockDiscount: 'Sichern Sie sich 20% Rabatt auf Ihre Nächste Reise',
    exclusivePromo: 'Exklusiver Aktionsgutschein',
    viewPromos: 'Alle Angebote Ansehen',
    spotlightTitle: 'Exklusive Luxusangebote',
    spotlightSub: 'Handverlesene Villen mit zeitlich begrenzten Aktionspreisen und VIP-Vorteilen',
    flashSale: 'FLASH-SALE',

    // Catalog & Filters
    filterTitle: 'Filterauswahl',
    resetFilters: 'Zurücksetzen',
    maxPrice: 'Max. Preis / Nacht',
    anyPrice: 'Jeder Preis',
    guestRating: 'Bewertung',
    anyRating: 'Jede Bewertung',
    exceptional: '4.8★ & Höher (Außergewöhnlich)',
    superbRating: '4.5★ & Höher (Hervorragend)',
    veryGood: '4.0★ & Höher (Sehr Gut)',
    amenities: 'Exklusive Ausstattung',
    suitesFound: 'Suiten Gefunden',
    sortBy: 'Sortieren nach:',
    topRated: 'Beste Bewertung',
    priceLowHigh: 'Preis: Aufsteigend',
    priceHighLow: 'Preis: Absteigend',
    listView: 'Listenansicht',
    gridView: 'Rasteransicht',
    noHotelsFound: 'Keine Suiten entsprechen Ihren Filterkriterien.',
    clearFilters: 'Filter Zurücksetzen',

    // Amenities
    infinityPool: 'Infinity-Pool',
    privateBeach: 'Privatstrand',
    luxurySpa: 'Luxus-Spa',
    freeWifi: 'Kostenloses WLAN',
    butlerService: 'Butler-Service',
    helipadAccess: 'Hubschrauberlandeplatz',
    michelinDining: 'Michelin-Gastronomie',
    skiInSkiOut: 'Direkter Pistenzugang',
    privateJacuzzi: 'Privater Whirlpool',
    airportShuttle: 'VIP-Flughafentransfer',

    // Detail & Rooms
    roomDetails: 'Suiten- und Zimmerdetails',
    sleeps: 'Für bis zu',
    sqFt: 'm²',
    roomCapacity: 'Maximale Belegung',
    diningPackages: 'Verpflegung & Gastronomie-Pakete',
    curatedAddons: 'Optionale Luxus-Extras',
    stayDates: 'Reisedaten & Gäste',
    proceedCheckout: 'Zur Kasse Gehen',
    roomReservedNotice: 'ZIMMER FÜR DIESE DATEN BEREITS BELEGT',

    // Voucher & Receipt
    officialVoucher: 'Offizieller Aufenthaltsgutschein & Buchungsbeleg',
    verifiedAndPaid: 'GEPRÜFT & BEZAHLT',
    holdGuaranteed: 'GARANTIERTE RESERVIERUNG • ZAHLUNG VOR ORT',
    bookingReference: 'Buchungsreferenz',
    issuedDate: 'Ausgestellt am',
    primaryGuest: 'Hauptgast-Details',
    accommodationDetails: 'Unterkunftsdetails',
    checkInDate: 'Anreisedatum',
    checkOutDate: 'Abreisedatum',
    stayDuration: 'Aufenthaltsdauer',
    occupancy: 'Belegung',
    paymentBreakdown: 'Zahlungs- & Rechnungsübersicht',
    totalPaid: 'Gesamtbetrag Bezahlt',
    totalPayable: 'Gesamtbetrag Zu Zahlen',
    instantCheckInQr: 'Sofortiger QR-Code Check-In',
    presentQrNotice: 'Zeigen Sie diesen Beleg oder QR-Code beim Check-in an der Rezeption vor.',
    luxeStayVerified: 'LuxeStay Verifiziert',
    guaranteedBooking: '100% Garantierte Buchung',
    needHelp: 'Brauchen Sie Hilfe? 24/7 Concierge:',
    printVoucher: 'Gutschein Drucken / Als PDF Speichern',

    // Auth & Accounts
    welcomeBack: 'Willkommen Zurück',
    createAccount: 'LuxeStay Konto Erstellen',
    customerAccount: 'Kundenkonto',
    partnerPortal: 'Partnerportal',
    guestAccount: 'Gastkonto',
    fullNameLabel: 'VOLLSTÄNDIGER NAME *',
    emailLabel: 'E-MAIL-ADRESSE *',
    passwordLabel: 'PASSWORT *',
    forgotPassword: 'Passwort vergessen?',
    continueGoogle: 'Mit Google Fortfahren',
    signUpGoogle: 'Mit Google Registrieren',
    adminDemo: '⚡ 1-Klick Super-Admin Demo-Login',
    managerDemo: '⚡ 1-Klick Hotelpartner Demo-Login',
    customerDemo: '⚡ 1-Klick VIP-Kunde Demo-Login',
    noAccount: 'Noch kein Konto bei LuxeStay?',
    haveAccount: 'Bereits ein Konto vorhanden?',
    registerNow: 'JETZT REGISTRIEREN',
    signInNow: 'JETZT ANMELDEN',
    profilePicture: 'Profilbild',
    optionalUpload: 'Optionaler Foto-Upload',

    // Footer & Trust
    footerBrandDesc: 'Der weltweit führende Marktplatz für Überwasser-Bungalows, 5-Sterne-Klippensuiten, traditionelle japanische Ryokans und hochalpine Chalets.',
    legalTrust: 'Rechtliches & Vertrauen',
    allRightsReserved: '© 2026 LuxeStay. Alle Rechte vorbehalten.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('luxestay_lang') || 'EN';
  });

  const setLanguage = (langCode) => {
    if (LANGUAGES[langCode]) {
      setLanguageState(langCode);
      localStorage.setItem('luxestay_lang', langCode);
      
      document.documentElement.dir = LANGUAGES[langCode].dir;
      document.documentElement.lang = langCode.toLowerCase();
    }
  };

  useEffect(() => {
    if (LANGUAGES[language]) {
      document.documentElement.dir = LANGUAGES[language].dir;
      document.documentElement.lang = language.toLowerCase();
    }
  }, [language]);

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
